apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  project: spof-cluster
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.16.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/values.yaml
    - repoURL: "https://github.com/SP0Fs/cert-manager-k8s.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/SP0Fs/cert-manager-k8s.git"
      targetRevision: HEAD
      path: resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
